global.params.p1=1111
global.params.p2=2222

spring.cloud.config.server.git.default-label=main

spring.h2.console.enabled=true
spring.cloud.config.enabled=true
spring.cloud.discovery.enabled=true

spring.data.rest.base-path=/api
management.endpoints.web.exposure.include=*

management.endpoint.web.exposure.include=health refresh

# Réduit le délai d'enregistrement en développement
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.client.registry-fetch-interval-seconds=5