customer.params.x=333333
customer.params.y=444444

spring.datasource.url=jdbc:h2:mem:customers-db
spring.h2.console.enabled=true

spring.cloud.discovery.enabled=true


spring.data.rest.base-path=/api

management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# Réduit le délai d'enregistrement en développement
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.client.registry-fetch-interval-seconds=5

spring.data.rest.default-media-type=application/json
spring.hateoas.use-hal-as-default-json-media-type=false

management.endpoint.web.exposure.include=health refresh