spring.application.name=discovery-service
server.port=8761
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Réduit le délai de détection des services tombés
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=3000